apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: client
spec:
  type: NodePort #LoadBalancer
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    nodePort: 32124
    port: 9200
    protocol: TCP
